using UnityEngine;
using System.Collections;
using SocketIO;


public class NetworkScript : MonoBehaviour {

    public GameScript game;
    public string clientID;
    public bool connected;

    public bool pingSent;
    public float pingResponseTime;
    public float pingTime = 3f; //how often in seconds to check for pings
    public float pingTimer;

    static SocketIOComponent socket;

	// Use this for initialization
	void Start () {
        game = GetComponent<GameScript>();

        socket = GetComponent<SocketIOComponent>();
        socket.On("connected", OnConnected);
        socket.On("disconnected", OnDisconencted);
        socket.On("spawn", OnSpawned);
        socket.On("pong", OnPong);
    }

    void OnConnected (SocketIOEvent e)
    {
        Debug.Log("connected to server through socket.io");
        Debug.Log(e.data);
        //store client id as generated by server
        clientID = e.data["id"].ToString();
        connected = true;
    }

    void OnDisconencted(SocketIOEvent e)
    {
        Debug.Log("connection lost to server through socket.io");
        connected = false;
    }

    void OnSpawned (SocketIOEvent e)
    {
        Debug.Log("received spawn message from server");
    }

    void OnPong(SocketIOEvent e)
    {
        Debug.Log("received ping response from server");
        Debug.Log("ping: " + Mathf.Floor(pingResponseTime*1000));
        pingSent = false;
    }

    
    public void SendSpawnMessage() //called by gamescript
    {

    }

	// Update is called once per frame
	void Update () {

        //do ping loop
        if (pingTimer > pingTime)
        {
            pingTimer = 0;
            if (connected == true)
            {
                Debug.Log("ping sent");
                socket.Emit("ping");
                pingSent = true;
                pingResponseTime = 0;
            }
            else
            {
                Debug.Log("not connected to server so cant ping it");
            }
        }
        pingTimer += Time.deltaTime;

        if (pingSent == true)
        {
            pingResponseTime += Time.deltaTime;
        }
	}
}
